# Info about the add-on
name: Imgproxy
version: "1.0.0"
slug: imgproxy
description: Imgproxy Add-on for Home Assistant
arch:
  - "armhf"
  - "armv7"
  - "aarch64"
  - "amd64"
  - "i386"
startup: "services"
boot: "auto"
host_network: true
homeassistant_api: true
options: {}
schema: {}

# Map specific folders or files
map:
  config: ro
  ssl: ro
  addons: ro
  backup: ro
  share: rw

# Docker configuration
ports:
  8080/tcp: 8080
image: "darthsim/imgproxy:latest"
privileged: false
environment:
  - IMGPROXY_LOG_LEVEL=info
  - IMGPROXY_MAX_SRC_RESOLUTION=3840x2160
  - IMGPROXY_MAX_SRC_FILE_SIZE=20MB
  - IMGPROXY_ENABLE_DEBUG=true  # Optional: Enable debug mode for troubleshooting
  - IMGPROXY_PRESERVE_HEADERS=true
  - IMGPROXY_ALLOWED_SOURCES=http://192.168.1.231:8123  # Allow Home Assistant as a source
  - IMGPROXY_BASE_URL=http://192.168.1.231:8080  # Base URL for Imgproxy

# Add-on metadata
ingress: false
ingress_port: 8099
webui: http://[HOST]:[PORT:8080]/
host_ipc: false
host_dbus: false

# Additional settings
apparmor: true

