# Example add-on for Imgproxy
name: Imgproxy
slug: imgproxy
description: Imgproxy Add-on for Home Assistant
url: "https://github.com/landonr/home-assistant-imgproxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  signature_key: "your_signature_key"
  port: "port"
schema:
  signature_key: "str?"
ports:
  8080/tcp: 8080
version: latest
image: "darthsim/imgproxy"