{
  "name": "Imgproxy",
  "version": "1.0.0",
  "slug": "imgproxy",
  "description": "Imgproxy Add-on for Home Assistant",
  "arch": ["armhf", "armv7", "amd64", "aarch64"],
  "image": "darthsim/imgproxy"
}
