# Add-on for Imgproxy
name: Imgproxy
slug: imgproxy
description: Imgproxy Add-on for Home Assistant
url: "https://github.com/landonr/home-assistant-imgproxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
ports:
  8080/tcp: 8080
version: latest
image: "darthsim/imgproxy"
