# Add-on for Imgproxy
name: Imgproxy
slug: imgproxy
description: Imgproxy Add-on for Home Assistant
url: "https://github.com/jbcurran/home-assistant-imgproxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
boot: auto
map:
  - share:rw
schema:
  signature_key: "str?"
ports:
  8080/tcp: 8080
version: latest
image: "darthsim/imgproxy"
environment:
  IMGPROXY_LOG_LEVEL: "info"
  IMGPROXY_MAX_SRC_RESOLUTION: "3840x2160"
  IMGPROXY_MAX_SRC_FILE_SIZE: "20MB"
  IMGPROXY_ENABLE_DEBUG: "true"  # Values should be strings
  IMGPROXY_PRESERVE_HEADERS: "true"
  IMGPROXY_ALLOWED_SOURCES: "http://192.168.1.231:8123"



